In [1]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv(r'C:\Users\LEGION\Desktop\Externship_SmartBridge\data.csv')

na = pd.notnull(df["Position"])
df = df[na]

df.head()

Unnamed: 0      ID               Name  Age  \
0           0  158023           L. Messi   31   
1           1   20801  Cristiano Ronaldo   33   
2           2  190871          Neymar Jr   26   
3           3  193080             De Gea   27   
4           4  192985       K. De Bruyne   27   

                                            Photo Nationality  \
0  https://cdn.sofifa.org/players/4/19/158023.png   Argentina   
1   https://cdn.sofifa.org/players/4/19/20801.png    Portugal   
2  https://cdn.sofifa.org/players/4/19/190871.png      Brazil   
3  https://cdn.sofifa.org/players/4/19/193080.png       Spain   
4  https://cdn.sofifa.org/players/4/19/192985.png     Belgium   

                                  Flag  Overall  Potential  \
0  https://cdn.sofifa.org/flags/52.png       94         94   
1  https://cdn.sofifa.org/flags/38.png       94         94   
2  https://cdn.sofifa.org/flags/54.png       92         93   
3  https://cdn.sofifa.org/flags/45.png       91         93   
4   https://cdn.sofifa.org/flags/7.png       91         92   

                  Club  ... Composure Marking StandingTackle  SlidingTackle  \
0         FC Barcelona  ...      96.0    33.0           28.0           26.0   
1             Juventus  ...      95.0    28.0           31.0           23.0   
2  Paris Saint-Germain  ...      94.0    27.0           24.0           33.0   
3    Manchester United  ...      68.0    15.0           21.0           13.0   
4      Manchester City  ...      88.0    68.0           58.0           51.0   

  GKDiving  GKHandling  GKKicking  GKPositioning GKReflexes Release Clause  
0      6.0        11.0       15.0           14.0        8.0        €226.5M  
1      7.0        11.0       15.0           14.0       11.0        €127.1M  
2      9.0         9.0       15.0           15.0       11.0        €228.1M  
3     90.0        85.0       87.0           88.0       94.0        €138.6M  
4     15.0        13.0        5.0           10.0       13.0        €196.4M  

[5 rows x 89 columns]

In [5]:
forward = ["ST", "LW", "RW", "LF", "RF", "RS","LS", "CF"]
midfielder = ["CM","RCM","LCM", "CDM","RDM","LDM", "CAM", "LAM", "RAM", "RM", "LM"]
defender = ["CB", "RCB", "LCB", "LWB", "RWB", "LB", "RB"]

In [6]:
df.loc[df["Position"] == "GK", "Position"] = 0
df.loc[df["Position"].isin(defender), "Position"] = 1
df.loc[df["Position"].isin(midfielder), "Position"] = 2
df.loc[df["Position"].isin(forward), "Position"] = 3

In [7]:
df["Position"].value_counts()

2    6838
1    5866
3    3418
0    2025
Name: Position, dtype: int64

In [8]:
df["Position"].unique()

array([3, 0, 2, 1], dtype=object)

In [9]:
df = df[["Position", 'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes']]
df.head()

Position  Finishing  HeadingAccuracy  ShortPassing  Volleys  Dribbling  \
0        3       95.0             70.0          90.0     86.0       97.0   
1        3       94.0             89.0          81.0     87.0       88.0   
2        3       87.0             62.0          84.0     84.0       96.0   
3        0       13.0             21.0          50.0     13.0       18.0   
4        2       82.0             55.0          92.0     82.0       86.0   

   Curve  FKAccuracy  LongPassing  BallControl  ...  Penalties  Composure  \
0   93.0        94.0         87.0         96.0  ...       75.0       96.0   
1   81.0        76.0         77.0         94.0  ...       85.0       95.0   
2   88.0        87.0         78.0         95.0  ...       81.0       94.0   
3   21.0        19.0         51.0         42.0  ...       40.0       68.0   
4   85.0        83.0         91.0         91.0  ...       79.0       88.0   

   Marking  StandingTackle  SlidingTackle  GKDiving  GKHandling  GKKicking  \
0     33.0            28.0           26.0       6.0        11.0       15.0   
1     28.0            31.0           23.0       7.0        11.0       15.0   
2     27.0            24.0           33.0       9.0         9.0       15.0   
3     15.0            21.0           13.0      90.0        85.0       87.0   
4     68.0            58.0           51.0      15.0        13.0        5.0   

   GKPositioning  GKReflexes  
0           14.0         8.0  
1           14.0        11.0  
2           15.0        11.0  
3           88.0        94.0  
4           10.0        13.0  

[5 rows x 34 columns]

In [10]:
x = df.drop("Position", axis = 1)

from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

x = pd.DataFrame(ss.fit_transform(x))

y = df["Position"]

x.head()

0         1         2         3         4         5         6   \
0  2.532391  1.018293  2.130190  2.434969  2.201010  2.491028  2.925359   
1  2.481180  2.111424  1.517765  2.491481  1.725114  1.838695  1.895584   
2  2.122700  0.558028  1.721906  2.321945  2.148132  2.219223  2.524891   
3 -1.666942 -1.800833 -0.591700 -1.690394 -1.976298 -1.422972 -1.365369   
4  1.866643  0.155296  2.266284  2.208922  1.619359  2.056139  2.296052   

         7         8         9   ...        23        24        25        26  \
0  2.236808  2.255005  1.767403  ...  1.684657  3.265669 -0.717896 -0.909470   
1  1.584271  2.135138  1.633444  ...  2.321491  3.178232 -0.969153 -0.770985   
2  1.649524  2.195072  1.968342  ...  2.066757  3.090795 -1.019405 -1.094116   
3 -0.112327 -0.981399 -0.509905  ... -0.544262  0.817436 -1.622423 -1.232601   
4  2.497823  1.955338  0.896668  ...  1.939390  2.566174  1.040907  0.475378   

         27        28        29        30        31        32  
0 -0.923850 -0.599889 -0.318983 -0.074713 -0.140266 -0.485159  
1 -1.064778 -0.543386 -0.318983 -0.074713 -0.140266 -0.318094  
2 -0.595016 -0.430379 -0.437259 -0.074713 -0.081569 -0.318094  
3 -1.534540  4.146377  4.057254  4.287959  4.203333  4.304052  
4  0.250555 -0.091360 -0.200706 -0.680640 -0.375055 -0.206717  

[5 rows x 33 columns]

In [11]:
y.head()

0    3
1    3
2    3
3    0
4    2
Name: Position, dtype: object

In [12]:
from keras.utils.np_utils import to_categorical
y_cat = to_categorical(y)

y_cat[:10]

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]], dtype=float32)

In [13]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x.values, y_cat,
                                                    test_size=0.2)

In [14]:
y.shape

(18147,)

In [15]:
x.shape

(18147, 33)

In [17]:
import tensorflow as tf

In [18]:
import keras as ks

In [19]:
from keras.models import Sequential
from keras.layers import Dense

In [25]:
K.clear_session()
model = Sequential()
model.add(Dense(60, input_shape = (33,), activation = "relu"))
model.add(Dense(15, activation = "relu"))
model.add(Dense(4, activation = "softmax"))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 60)                2040      
                                                                 
 dense_1 (Dense)             (None, 15)                915       
                                                                 
 dense_2 (Dense)             (None, 4)                 64        
                                                                 
Total params: 3,019
Trainable params: 3,019
Non-trainable params: 0
_________________________________________________________________


In [26]:
60 * 33 + 60

2040

In [28]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [29]:
model.fit(x_train, y_train, verbose=1, epochs=10)

Epoch 1/10
454/454 [==============================] - 1s 1ms/step - loss: 0.2288 - accuracy: 0.8178
Epoch 2/10
454/454 [==============================] - 0s 1ms/step - loss: 0.1541 - accuracy: 0.8693
Epoch 3/10
454/454 [==============================] - 0s 1ms/step - loss: 0.1487 - accuracy: 0.8749
Epoch 4/10
454/454 [==============================] - 0s 980us/step - loss: 0.1451 - accuracy: 0.8786
Epoch 5/10
454/454 [==============================] - 0s 1ms/step - loss: 0.1429 - accuracy: 0.8797
Epoch 6/10
454/454 [==============================] - 0s 1ms/step - loss: 0.1418 - accuracy: 0.8820
Epoch 7/10
454/454 [==============================] - 0s 836us/step - loss: 0.1399 - accuracy: 0.8839
Epoch 8/10
454/454 [==============================] - 0s 875us/step - loss: 0.1386 - accuracy: 0.8843
Epoch 9/10
454/454 [==============================] - 0s 1ms/step - loss: 0.1380 - accuracy: 0.8848
Epoch 10/10
454/454 [==============================] - 0s 1ms/step - loss: 0.1359 - accuracy: 

In [31]:
y_pred = model.predict(x_test)

In [34]:
y_pred

array([[6.3277874e-08, 9.9917942e-01, 8.0763013e-04, 1.2851263e-05],
       [1.0929639e-06, 6.4566535e-05, 3.8207141e-01, 6.1786288e-01],
       [2.9408051e-10, 9.9999118e-01, 8.7685439e-06, 5.6491814e-08],
       ...,
       [1.7732805e-12, 9.9999952e-01, 4.2095741e-07, 3.3925218e-09],
       [1.5273802e-08, 9.9991679e-01, 8.0377293e-05, 2.8698012e-06],
       [4.6400728e-09, 2.6322560e-09, 1.0739982e-07, 9.9999988e-01]],
      dtype=float32)

In [36]:
x_test[0]

array([-0.79634878,  0.2128287 ,  0.08877229, -0.95574017, -0.28422393,
        0.0447782 , -1.13653014,  0.21394185, -0.20226495,  0.22687154,
        0.49645619, -0.37250072, -1.31388296, -0.42193162, -1.01335311,
        0.07688763, -0.0768485 , -0.4237224 , -0.68075852, -0.10803073,
        0.49752589, -0.56130243, -0.66503926, -0.41689514, -0.31924311,
        0.43788897,  0.5215392 ,  0.48543629, -0.48688246, -0.4963977 ,
       -0.19589859, -0.55114708, -0.54084783])

In [37]:
y_test[0]

array([0., 1., 0., 0.], dtype=float32)

In [38]:
predict=model.predict([[-0.79634878,  0.2128287 ,  0.08877229, -0.95574017, -0.28422393,
        0.0447782 , -1.13653014,  0.21394185, -0.20226495,  0.22687154,
        0.49645619, -0.37250072, -1.31388296, -0.42193162, -1.01335311,
        0.07688763, -0.0768485 , -0.4237224 , -0.68075852, -0.10803073,
        0.49752589, -0.56130243, -0.66503926, -0.41689514, -0.31924311,
        0.43788897,  0.5215392 ,  0.48543629, -0.48688246, -0.4963977 ,
       -0.19589859, -0.55114708, -0.54084783]])

In [40]:
predict>0.5

array([[False,  True, False, False]])